### ISSUE TITLE
Missing version 5.0.3 ?

### ISSUE THREAD

**Issue by rnavarropiris** [mhgrove/cp-common-utils#11]
Hi!

I'm using the stardog libraries, which use cp-common-utils as dependency. In the latest version of Stardog (4.1.3), the used cp-common-utils is version 5.0.3 which does not exist in this repository as of this moment.

Is this repository out of date? Or what this mean?

Cheers!

Ruben

**Comment by mhgrove** [comment]
We forgot to push the tag, it's available now.

**Comment by rnavarropiris** [comment]
great, thanks for the quick reply! :)
